### ISSUE TITLE
Error message for "AWS::Serverless::Application" resource with "Fn::FindInMap" 

### ISSUE THREAD

**Issue by ylynn** [aws/serverless-application-model#1606]
**Description:**

Error message for "AWS::Serverless::Application" resource with "Fn::FindInMap" is "TypeError: unhashable type: 'list'", which is not helpful.

**Steps to reproduce the issue:**
Parts of the template

```yaml
Parameters:
  SemVer:
    Type: String
    Default: 1.0.0

Mappings:
  MyMap:
    appId:
      appIdValue: arn:aws:serverlessrepo:us-east-1:1234xxx:applications/anotherApp
    version:
      versionValue:
      - Ref: Semver

Resources:
  myApp:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId:
          Fn::FindInMap:
          - MyMap
          - appId
          - appIdValue
        SemanticVersion:
          Fn::FindInMap:
          - MyMap
          - version
          - versionValue
```

**Observed result:**
TypeError: unhashable type: 'list'

**Expected result:**

**Comment by mateuszowolf** [comment]
I think it might be this part 
```
version:
    versionValue
    - Ref: Semver
```
which should look like this:
```
version:
    versionValue: !Ref Semver
```

**Comment by vtuhtan** [comment]
I believe I ran into the same/similar bug with more descriptive error. I'm using `FindInMap` intrinsic function for resolving ApplicationId property of AWS::Serverless::Application.

Here's error message and resource definition (stack trace available on the bottom):
```
raise InvalidDocumentException(document_errors)
samtranslator.model.exceptions.InvalidDocumentException: 
[InvalidResourceException('CertificateFactoryCertificates', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")]
```

```
CertificateFactoryCertificates:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !FindInMap [ "Environment", !Ref Environment, "SARApplicationId" ]
        SemanticVersion: !Ref CertificateFactoryVersion
```

Traceback:
```
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 148, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 114, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 129, in cli
    mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 179, in do_cli
    mode=mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 62, in __enter__
    self._function_provider = SamFunctionProvider(self._template_dict, self._parameter_overrides)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\providers\sam_function_provider.py", line 40, in __init__
    self.template_dict = SamFunctionProvider.get_template(template_dict, parameter_overrides)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\providers\sam_base_provider.py", line 126, in get_template
    template_dict = SamTranslatorWrapper(template_dict, parameter_values=parameters_values).run_plugins()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\samlib\wrapper.py", line 79, in run_plugins
    functools.reduce(lambda message, error: message + " " + str(error), e.causes, str(e))
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('CertificateFactoryCertificates', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")] ('CertificateFactoryCertificates', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")
```

**Comment by hoffa** [comment]
You might be able to get this to work by adding [`AWS::LanguageExtensions`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html) to `Transform` as such:

```yaml
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
```

`AWS::LanguageExtensions` [resolves intrinsic functions](https://aws.amazon.com/blogs/mt/introducing-new-language-extensions-in-aws-cloudformation/) if the value is known when `Transform`s are run.

See https://github.com/aws/serverless-application-model/issues/2533 for more information.

**Comment by hoffa** [comment]
Closing in favor of https://github.com/aws/serverless-application-model/issues/2533.
