### ISSUE TITLE
Intrinsic Function fails on AWS::Serverless::LayerVersion

### ISSUE THREAD

**Issue by ronaldour** [aws/serverless-application-model#1612]
**Description:**

I tried using the intrinsic function _If_ in the Retention policy property of AWS::Serverless::LayerVersion but the _Internal transform failure_ shows on `sam deploy`
Here is the code sinppet of my template

```yml
---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

  Environment:
    Type: String
    Default: dev
    Description: Environment name to append to resources names and tags

Conditions:

  IsProd: !Equals [ !Ref Environment, "prod" ]

Resources:

  ExpressJsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub express-js-${Environment}
      Description: NodeJs dependencies for a lambda ExpressJs application
      CompatibleRuntimes:
      - nodejs12.x
      ContentUri: ./layers/express
      RetentionPolicy: !If [ IsProd, Retain, Delete ]
    Metadata:
      BuildMethod: nodejs12.x
```
I tried different syntax versions for the intrinsic function (Fn::If) but got the same issue.
I found the #22 Issue and was wondering if this should work or not.

**Steps to reproduce the issue:**
Add the *If* Intrinsic function to the RetentionPolicy property of AWS::Serverless::LayerVersion and execute `sam deploy`

**Observed result:**
```console
Error: Failed to create changeset for the stack: my-stack, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure
```
**Expected result:**
Stack created

**Comment by ronaldour** [comment]
I just ran `sam validate` for the file mentioned above and noticed that it fails on
```console
if self.RetentionPolicy is None or self.RetentionPolicy.lower() == self.RETAIN.lower():
AttributeError: 'dict' object has no attribute 'lower'
```
So I believe it is a bug, unless this is the expected behavior
Full StackTrace of the error:
```console
$ sam validate
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\validate\validate.py", line 27, in cli
    do_cli(ctx, template_file)  # pragma: no cover
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\validate\validate.py", line 47, in do_cli
    validator.is_valid()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\validate\lib\sam_template_validator.py", line 60, in is_valid
    template = sam_translator.translate(sam_template=self.sam_template, parameter_values={})
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\translator\translator.py", line 122, in translate
    translated = macro.to_cloudformation(**kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\model\sam_resources.py", line 1037, in to_cloudformation
    resources.append(self._construct_lambda_layer(intrinsics_resolver))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\model\sam_resources.py", line 1055, in _construct_lambda_layer
    retention_policy_value = self._get_retention_policy_value()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\model\sam_resources.py", line 1095, in _get_retention_policy_value
    if self.RetentionPolicy is None or self.RetentionPolicy.lower() == self.RETAIN.lower():
AttributeError: 'dict' object has no attribute 'lower'
```

**Comment by mndeveci** [comment]
Hi @ronaldour ,

We have released support for `DeletionPolicy` attribute in [SAM v1.24.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.24.0). You can now use `DeletionPolicy` directly and it will be a pass-through parameter to CFN, and it should resolve the intrinsic function. 

For `AWS::Serverless::LayerVersion`; `RetentionPolicy` property has higher precedence than the `DeletionPolicy` for keeping backwards compatibility. For that reason, if you use `DeletionPolicy`, you need to remove `RetentionPolicy` from the properties. Please see the example below.


```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

  Environment:
    Type: String
    Default: dev
    Description: Environment name to append to resources names and tags

Conditions:

  IsProd: !Equals [ !Ref Environment, "prod" ]

Resources:

  ExpressJsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub express-js-${Environment}
      Description: NodeJs dependencies for a lambda ExpressJs application
      CompatibleRuntimes:
      - nodejs12.x
      ContentUri: ./layers/express
    DeletionPolicy: !If [ IsProd, Retain, Delete ]
    Metadata:
      BuildMethod: nodejs12.x
```

I am resolving this for now, but please feel free to re-open if you see any issues.

Thanks!
