### ISSUE TITLE
`sam validate` throws AttributeError. Blocks subsequent `sam build`

### ISSUE THREAD

**Issue by xirkus** [aws/serverless-application-model#1913]
### Description:
When `sam validate` is run against, the following error is encountered:

```
 % sam validate --profile=mel --region=us-east-1
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.16.0', 'console_scripts', 'sam')())
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 152, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 121, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 32, in cli
    do_cli(ctx, template_file)  # pragma: no cover
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 52, in do_cli
    validator.is_valid()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/lib/sam_template_validator.py", line 61, in is_valid
    template = sam_translator.translate(sam_template=self.sam_template, parameter_values={})
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samtranslator/translator/translator.py", line 95, in translate
    sam_parameter_values.add_pseudo_parameter_values()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samtranslator/sdk/parameter.py", line 73, in add_pseudo_parameter_values
    if region.startswith("cn-"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Afterwards, attempting to run `sam build` results in the following error:

```
% sam build                                    
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.16.0', 'console_scripts', 'sam')())
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 152, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 121, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 156, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 246, in do_cli
    artifacts = builder.build()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 122, in build
    build_graph = self._get_build_graph()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 158, in _get_build_graph
    build_graph = BuildGraph(self._build_dir)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_graph.py", line 152, in __init__
    self._read()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_graph.py", line 255, in _read
    document = tomlkit.loads(txt)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/api.py", line 34, in loads
    return parse(string)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/api.py", line 51, in parse
    return Parser(string).parse()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/parser.py", line 160, in parse
    key, value = self._parse_table()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/parser.py", line 1165, in _parse_table
    key_next, table_next = self._parse_table(name, table)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/parser.py", line 1165, in _parse_table
    key_next, table_next = self._parse_table(name, table)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/parser.py", line 1165, in _parse_table
    key_next, table_next = self._parse_table(name, table)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/parser.py", line 1152, in _parse_table
    item = self._parse_item()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/parser.py", line 306, in _parse_item
    return self._parse_key_value(True)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/parser.py", line 397, in _parse_key_value
    val = self._parse_value()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/parser.py", line 569, in _parse_value
    return self._parse_array()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/tomlkit/parser.py", line 737, in _parse_array
    raise self.parse_error(UnexpectedCharError, self._current)
tomlkit.exceptions.UnexpectedCharError: Unexpected character: 'R' at line 14 col 19
```

The problem seems to be with the generated `.aws-sam/build.toml` file. This is what mine looks like when this issue occurs:

```
# This file is auto generated by SAM CLI build command

[function_build_definitions]
[function_build_definitions.600956d6-2522-42b6-8f81-001280c2b700]
packagetype = "Image"
functions = ["Process"]

[function_build_definitions.600956d6-2522-42b6-8f81-001280c2b700.metadata]
DockerTag = "v1"
DockerContext = "./function"
Dockerfile = "Dockerfile"

[function_build_definitions.600956d6-2522-42b6-8f81-001280c2b700.metadata.DockerName]
"Fn::Join" = ["-", Ref = "DeploymentStage"
, Ref = "ApplicationPrefix"
, "process"]

[layer_build_definitions]

```

### Steps to reproduce:
See above.

### Observed result:

Here's the the command with `--debug`:

```
 % sam validate --profile=mel --region=us-east-1 --debug 
2021-02-06 17:27:50,975 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.16.0', 'console_scripts', 'sam')())
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 152, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 121, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 32, in cli
    do_cli(ctx, template_file)  # pragma: no cover
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 52, in do_cli
    validator.is_valid()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/lib/sam_template_validator.py", line 61, in is_valid
    template = sam_translator.translate(sam_template=self.sam_template, parameter_values={})
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samtranslator/translator/translator.py", line 95, in translate
    sam_parameter_values.add_pseudo_parameter_values()
  File "/usr/local/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samtranslator/sdk/parameter.py", line 73, in add_pseudo_parameter_values
    if region.startswith("cn-"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Expected result:
Not to fail ;-)

> ***WORK-AROUND: Delete the `.aws-sam` directory. This should allow you to proceed without errors (unless you run this command again)***

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 11.2
2. `SAM CLI, version 1.16.0`
3. AWS region: us-east-1

**Comment by jfuss** [comment]
Transferring to the correct repo.
