### ISSUE TITLE
cant aws build because requirements 

### ISSUE THREAD

**Issue by tyoc213** [aws/serverless-application-model#1926]
### Description:
Trying `aws build` I got _generate_egg_info IndexError: list index out of range

### Steps to reproduce:

my requirements.txt is

```
fastai==2.2.5
requests==2.25.1
torch==1.7.1
torchvision==0.8.2

```

And it happens as this

```
21:51 $ sam build --debug
2021-02-14 21:51:53,174 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-02-14 21:51:53,283 | 'build' command is called
2021-02-14 21:51:53,290 | No Parameters detected in the template
2021-02-14 21:51:53,314 | 2 resources found in the stack 
2021-02-14 21:51:53,314 | No Parameters detected in the template
2021-02-14 21:51:53,336 | No Parameters detected in the template
2021-02-14 21:51:53,358 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2021-02-14 21:51:53,358 | No Parameters detected in the template
2021-02-14 21:51:53,380 | Instantiating build definitions
2021-02-14 21:51:53,383 | Same function build definition found, adding function (Previous: BuildDefinition(python3.8, hello_world/, Zip, , 9b35a7d4-0925-4c4e-aefb-311c41ade239, {}, []), Current: BuildDefinition(python3.8, hello_world/, Zip, , b24851eb-04f1-48f5-b99f-be68a186690a, {}, []), Function: Function(name='HelloWorldFunction', functionname='HelloWorldFunction', runtime='python3.8', memory=None, timeout=3, handler='app.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='hello_world/', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api', 'Properties': {'Path': '/hello', 'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, inlinecode=None, codesign_config_arn=None, stack_path=''))
2021-02-14 21:51:53,384 | Building codeuri: hello_world/ runtime: python3.8 metadata: {} functions: ['HelloWorldFunction']
2021-02-14 21:51:53,384 | Building to following folder /home/tyoc213/Documents/github/aws-lamda/hello-world/.aws-sam/build/HelloWorldFunction
2021-02-14 21:51:53,385 | Loading workflow module 'aws_lambda_builders.workflows'
2021-02-14 21:51:53,387 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-02-14 21:51:53,388 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2021-02-14 21:51:53,389 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2021-02-14 21:51:53,390 | Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
2021-02-14 21:51:53,391 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2021-02-14 21:51:53,392 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2021-02-14 21:51:53,393 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2021-02-14 21:51:53,394 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2021-02-14 21:51:53,395 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2021-02-14 21:51:53,395 | Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-02-14 21:51:53,419 | Running workflow 'PythonPipBuilder'
2021-02-14 21:51:53,419 | Running PythonPipBuilder:ResolveDependencies
2021-02-14 21:51:53,441 | calling pip download -r /home/tyoc213/Documents/github/aws-lamda/hello-world/hello_world/requirements.txt --dest /tmp/tmpv0146wo2
2021-02-14 21:52:10,215 | PythonPipBuilder:ResolveDependencies raised unhandled exception
Traceback (most recent call last):
  File "aws_lambda_builders/workflow.py", line 269, in run
  File "aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 204, in build_site_packages
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 228, in _download_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 311, in _download_all_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 311, in <setcomp>
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 417, in __init__
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 459, in _calculate_name_and_version
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 517, in get_package_name_and_version
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 500, in _generate_egg_info
IndexError: list index out of range

Build Failed
2021-02-14 21:52:10,321 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '618195c1-f8a2-4315-acdd-0b8afb3d1f22', 'installationId': 'd8fe3a0c-6e3c-44d9-a45c-d7b7ecb2a03d', 'sessionId': 'dff8c019-afc4-4d1e-aaf1-87949ba88f2e', 'executionEnvironment': 'CLI', 'pyversion': '3.7.9', 'samcliVersion': '1.18.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 17145, 'exitReason': 'WorkflowUnknownError', 'exitCode': 1}}]}
2021-02-14 21:52:10,720 | Telemetry response: 200
Error: PythonPipBuilder:ResolveDependencies - list index out of range
```

### Expected result:

but if I eecute the command it works ok

```
21:52 $ mkdir /tmp/jojo
21:52 $ pip download -r /home/tyoc213/Documents/github/aws-lamda/hello-world/hello_world/requirements.txt --dest /tmp/jojo
Collecting fastai==2.2.5
  Using cached fastai-2.2.5-py3-none-any.whl (191 kB)
Collecting requests==2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting torch==1.7.1
  Using cached torch-1.7.1-cp38-cp38-manylinux1_x86_64.whl (776.8 MB)
Collecting torchvision==0.8.2
  Using cached torchvision-0.8.2-cp38-cp38-manylinux1_x86_64.whl (12.8 MB)
Collecting packaging
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting pyyaml
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting pip
  Using cached pip-21.0.1-py3-none-any.whl (1.5 MB)
Collecting scipy
  Using cached scipy-1.6.0-cp38-cp38-manylinux1_x86_64.whl (27.2 MB)
Collecting pandas
  Using cached pandas-1.2.2-cp38-cp38-manylinux1_x86_64.whl (9.7 MB)
Collecting matplotlib
  Using cached matplotlib-3.3.4-cp38-cp38-manylinux1_x86_64.whl (11.6 MB)
Collecting scikit-learn
  Using cached scikit_learn-0.24.1-cp38-cp38-manylinux2010_x86_64.whl (24.9 MB)
Collecting spacy
  Using cached spacy-3.0.3-cp38-cp38-manylinux2014_x86_64.whl (12.9 MB)
Collecting fastprogress>=0.2.4
  Using cached fastprogress-1.0.0-py3-none-any.whl (12 kB)
Collecting fastcore<1.4,>=1.3.8
  Using cached fastcore-1.3.19-py3-none-any.whl (53 kB)
Collecting pillow>6.0.0
  Using cached Pillow-8.1.0-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting numpy
  Using cached numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp38-cp38-manylinux1_x86_64.whl (1.2 MB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting pytz>=2017.3
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting joblib>=0.11
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting spacy-legacy<3.1.0,>=3.0.0
  Using cached spacy_legacy-3.0.1-py2.py3-none-any.whl (7.0 kB)
Collecting tqdm<5.0.0,>=4.38.0
  Using cached tqdm-4.56.2-py2.py3-none-any.whl (72 kB)
Collecting pydantic<1.8.0,>=1.7.1
  Using cached pydantic-1.7.3-cp38-cp38-manylinux2014_x86_64.whl (12.2 MB)
Collecting setuptools
  Using cached setuptools-53.0.0-py3-none-any.whl (784 kB)
Collecting catalogue<2.1.0,>=2.0.1
  Using cached catalogue-2.0.1-py3-none-any.whl (9.6 kB)
Collecting preshed<3.1.0,>=3.0.2
  Using cached preshed-3.0.5-cp38-cp38-manylinux2014_x86_64.whl (130 kB)
Collecting typer<0.4.0,>=0.3.0
  Using cached typer-0.3.2-py3-none-any.whl (21 kB)
Collecting blis<0.8.0,>=0.4.0
  Using cached blis-0.7.4-cp38-cp38-manylinux2014_x86_64.whl (9.8 MB)
Collecting cymem<2.1.0,>=2.0.2
  Using cached cymem-2.0.5-cp38-cp38-manylinux2014_x86_64.whl (35 kB)
Collecting murmurhash<1.1.0,>=0.28.0
  Using cached murmurhash-1.0.5-cp38-cp38-manylinux2014_x86_64.whl (20 kB)
Collecting wasabi<1.1.0,>=0.8.1
  Using cached wasabi-0.8.2-py3-none-any.whl (23 kB)
Collecting pathy
  Using cached pathy-0.3.6-py3-none-any.whl (36 kB)
Collecting thinc<8.1.0,>=8.0.0
  Using cached thinc-8.0.1-cp38-cp38-manylinux2014_x86_64.whl (1.1 MB)
Collecting srsly<3.0.0,>=2.4.0
  Using cached srsly-2.4.0-cp38-cp38-manylinux2014_x86_64.whl (458 kB)
Collecting jinja2
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting click<7.2.0,>=7.1.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-manylinux2010_x86_64.whl (32 kB)
Collecting smart-open<4.0.0,>=2.2.0
  Using cached smart_open-3.0.0.tar.gz (113 kB)
Saved /tmp/jojo/fastai-2.2.5-py3-none-any.whl
Saved /tmp/jojo/requests-2.25.1-py2.py3-none-any.whl
Saved /tmp/jojo/torch-1.7.1-cp38-cp38-manylinux1_x86_64.whl
Saved /tmp/jojo/torchvision-0.8.2-cp38-cp38-manylinux1_x86_64.whl
Saved /tmp/jojo/certifi-2020.12.5-py2.py3-none-any.whl
Saved /tmp/jojo/chardet-4.0.0-py2.py3-none-any.whl
Saved /tmp/jojo/fastcore-1.3.19-py3-none-any.whl
Saved /tmp/jojo/fastprogress-1.0.0-py3-none-any.whl
Saved /tmp/jojo/idna-2.10-py2.py3-none-any.whl
Saved /tmp/jojo/Pillow-8.1.0-cp38-cp38-manylinux1_x86_64.whl
Saved /tmp/jojo/urllib3-1.26.3-py2.py3-none-any.whl
Saved /tmp/jojo/matplotlib-3.3.4-cp38-cp38-manylinux1_x86_64.whl
Saved /tmp/jojo/cycler-0.10.0-py2.py3-none-any.whl
Saved /tmp/jojo/kiwisolver-1.3.1-cp38-cp38-manylinux1_x86_64.whl
Saved /tmp/jojo/numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl
Saved /tmp/jojo/pyparsing-2.4.7-py2.py3-none-any.whl
Saved /tmp/jojo/python_dateutil-2.8.1-py2.py3-none-any.whl
Saved /tmp/jojo/six-1.15.0-py2.py3-none-any.whl
Saved /tmp/jojo/packaging-20.9-py2.py3-none-any.whl
Saved /tmp/jojo/pandas-1.2.2-cp38-cp38-manylinux1_x86_64.whl
Saved /tmp/jojo/pytz-2021.1-py2.py3-none-any.whl
Saved /tmp/jojo/pip-21.0.1-py3-none-any.whl
Saved /tmp/jojo/PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl
Saved /tmp/jojo/scikit_learn-0.24.1-cp38-cp38-manylinux2010_x86_64.whl
Saved /tmp/jojo/joblib-1.0.1-py3-none-any.whl
Saved /tmp/jojo/scipy-1.6.0-cp38-cp38-manylinux1_x86_64.whl
Saved /tmp/jojo/threadpoolctl-2.1.0-py3-none-any.whl
Saved /tmp/jojo/spacy-3.0.3-cp38-cp38-manylinux2014_x86_64.whl
Saved /tmp/jojo/blis-0.7.4-cp38-cp38-manylinux2014_x86_64.whl
Saved /tmp/jojo/catalogue-2.0.1-py3-none-any.whl
Saved /tmp/jojo/cymem-2.0.5-cp38-cp38-manylinux2014_x86_64.whl
Saved /tmp/jojo/murmurhash-1.0.5-cp38-cp38-manylinux2014_x86_64.whl
Saved /tmp/jojo/preshed-3.0.5-cp38-cp38-manylinux2014_x86_64.whl
Saved /tmp/jojo/pydantic-1.7.3-cp38-cp38-manylinux2014_x86_64.whl
Saved /tmp/jojo/spacy_legacy-3.0.1-py2.py3-none-any.whl
Saved /tmp/jojo/srsly-2.4.0-cp38-cp38-manylinux2014_x86_64.whl
Saved /tmp/jojo/thinc-8.0.1-cp38-cp38-manylinux2014_x86_64.whl
Saved /tmp/jojo/tqdm-4.56.2-py2.py3-none-any.whl
Saved /tmp/jojo/typer-0.3.2-py3-none-any.whl
Saved /tmp/jojo/click-7.1.2-py2.py3-none-any.whl
Saved /tmp/jojo/wasabi-0.8.2-py3-none-any.whl
Saved /tmp/jojo/Jinja2-2.11.3-py2.py3-none-any.whl
Saved /tmp/jojo/MarkupSafe-1.1.1-cp38-cp38-manylinux2010_x86_64.whl
Saved /tmp/jojo/pathy-0.3.6-py3-none-any.whl
Saved /tmp/jojo/smart_open-3.0.0.tar.gz
Saved /tmp/jojo/typing_extensions-3.7.4.3-py3-none-any.whl
Saved /tmp/jojo/setuptools-53.0.0-py3-none-any.whl
Successfully downloaded fastai requests torch torchvision certifi chardet fastcore fastprogress idna pillow urllib3 matplotlib cycler kiwisolver numpy pyparsing python-dateutil six packaging pandas pytz pip pyyaml scikit-learn joblib scipy threadpoolctl spacy blis catalogue cymem murmurhash preshed pydantic spacy-legacy srsly thinc tqdm typer click wasabi jinja2 MarkupSafe pathy smart-open typing-extensions setuptools
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux Ubuntu 20.04 LTS
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.18.1
3. AWS region: local

**Comment by elbayaaa** [comment]
Hi @tyoc213 I am unable to reproduce your issue. Please add more details to the "**Steps to reproduce**" section.

Here is what I tried and `sum build` successfully worked for me:
```
sam --version 
  => SAM CLI, version 1.18.1
sam init
  AWS Quick Start Templates
  Zip (artifact is a zip uploaded to S3)
  python3.8
  Hello World Example
```

then updated the `hello_world/requirements.txt` with the information you provided.

Finally, ran `sam build` and it succeeded.
