### ISSUE TITLE
Publish fails for Schedule witth RetryPolicy

### ISSUE THREAD

**Issue by jakobbraun** [aws/serverless-application-model#1931]
### Description:
I try to configure a Lambda function in SAM with a RetryPolicy as described in the [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedule.html).
Deploying the application works as expected, but publishing  to the Serverless Application Repository fails with:
```
 property RetryPolicy not defined for resource of type Schedule
```

### Steps to reproduce:

1. Create a Labda function in SAM
2. Add schedule:
     ```
    Events:
            MinutelyTrigger:
              Type: Schedule
              Properties:
                Schedule: rate(1 minute)
                Description: Minutely trigger for the CloudWatch adapter
                Enabled: True
                RetryPolicy:
                  MaximumRetryAttempts: 0
                  MaximumEventAgeInSeconds: 60
    ```
3. run `sam package` and `sam publish`

### Observed result:

`sam publish` fails with the following message:

```
2021-02-17 03:11:29,504 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Publish Failed
2021-02-17 03:11:30,289 | Failed to publish application to serverlessrepo
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/serverlessrepo/publish.py", line 45, in publish_application
    response = sar_client.create_application(**request)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the CreateApplication operation: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [ExasolCloudWatchAdapterMinutelyTrigger] is invalid. property RetryPolicy not defined for resource of type Schedule

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/commands/publish/command.py", line 85, in do_cli
    publish_output = publish_application(template_data)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/serverlessrepo/publish.py", line 50, in publish_application
    raise _wrap_client_error(e)
serverlessrepo.exceptions.ServerlessRepoClientError: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [ExasolCloudWatchAdapterMinutelyTrigger] is invalid. property RetryPolicy not defined for resource of type Schedule
2021-02-17 03:11:30,295 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'a79ad44e-d26d-4318-b384-cafccc2352ee', 'installationId': 'f5cbbe8a-c477-4045-9748-87fa6825f3a5', 'sessionId': '5395d95d-8883-4b85-aae8-376fb68d0538', 'executionEnvironment': 'CLI', 'pyversion': '3.8.7', 'samcliVersion': '1.17.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'eu-central-1', 'commandName': 'sam publish', 'duration': 790, 'exitReason': 'ServerlessRepoClientError', 'exitCode': 1}}]}
2021-02-17 03:11:31,003 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [ExasolCloudWatchAdapterMinutelyTrigger] is invalid. property RetryPolicy not defined for resource of type Schedule
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html

```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: linux, Kubuntu 20.04
2. `sam --version`: SAM CLI, version 1.17.0
3. AWS region: eu-central-1

**Comment by Jacco** [comment]
I think this is simply solved by updating schema.json, which it what I did in my PR.

I added both RetryPolicy and DeadLetterConfig
