### ISSUE TITLE
SAM Validate fails on LayerName !Sub with numbers

### ISSUE THREAD

**Issue by MarkLedermannTR** [aws/serverless-application-model#2093]
### Description:
Recently upgraded from 1.24 to 1.26.0 (Windows), but I do not recall if "sam validate" was working with prior version.

When using !Sub in a LayerVersion LayerName, if the default value for a property being used in the substitution is all digits, the sam validate fails with a Type error. This is the case even if the property type is String. Behavior seems to be specific to LayerName. This may be an underlaying CloudFormation issue, but I haven't been able to determine for sure.

### Steps to reproduce:
Sample template:

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: see if SAM validate has a bug

Parameters:
  AppId:
    Type: String
    Default: 123456
    Description: App Id for the project used to tag the instance

Resources:

  CommonLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "a${AppId}-commonlib-layer"
      Description: Common libraries for Migration Automation
      ContentUri: dependencies/common
      CompatibleRuntimes:
        - python3.8
```
Run sam validate fails with 

`TypeError: sequence item 1: expected str instance, int found`

If you change the Default for AppId to include a alpha character (ie. "a123456") sam validate succeeds.

### Observed result:

sam validate --template buggy-template.yaml --debug
2021-07-16 09:09:59,581 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-07-16 09:09:59,583 | Using config file: samconfig.toml, config environment: default
2021-07-16 09:09:59,583 | Expand command line arguments to:
2021-07-16 09:09:59,583 | --template_file=C:\Projects\buggy-template.yaml
2021-07-16 09:10:00 Loading policies from IAM...
2021-07-16 09:10:01 Finished loading policies from IAM.
2021-07-16 09:10:01,642 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '282ae9a0-feea-4a66-b9ea-d6705cad0617', 'installationId': '21c2ecf5-230f-4e85-b830-49afa5045dc5', 'sessionId': 'ed8b15a2-c443-436d-b431-8d74a5d53be5', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.26.0', 'awsProfileProvided': True, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam validate', 'duration': 2069, 'exitReason': 'TypeError', 'exitCode': 255}}]}
2021-07-16 09:10:02,106 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\validate\validate.py", line 37, in cli
    do_cli(ctx, template_file)  # pragma: no cover
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\validate\validate.py", line 59, in do_cli
    validator.is_valid()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\validate\lib\sam_template_validator.py", line 68, in is_valid
    template = sam_translator.translate(sam_template=self.sam_template, parameter_values={})
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\translator\translator.py", line 136, in translate
    translated = macro.to_cloudformation(**kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\model\sam_resources.py", line 1153, in to_cloudformation
    resources.append(self._construct_lambda_layer(intrinsics_resolver))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\model\sam_resources.py", line 1164, in _construct_lambda_layer
    self.LayerName = self._resolve_string_parameter(intrinsics_resolver, self.LayerName, "LayerName")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\model\__init__.py", line 461, in _resolve_string_parameter
    value = intrinsics_resolver.resolve_parameter_refs(parameter_value)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\intrinsics\resolver.py", line 44, in resolve_parameter_refs
    return self._traverse(input, self.parameters, self._try_resolve_parameter_refs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\intrinsics\resolver.py", line 127, in _traverse
    input = resolver_method(input, resolution_data)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\intrinsics\resolver.py", line 180, in _try_resolve_parameter_refs
    return self.supported_intrinsics[function_type].resolve_parameter_refs(input, parameters)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\intrinsics\actions.py", line 192, in resolve_parameter_refs
    return self._handle_sub_action(input_dict, do_replacement)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\intrinsics\actions.py", line 325, in _handle_sub_action
    input_dict[key] = self._handle_sub_value(sub_value, handler)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\intrinsics\actions.py", line 344, in _handle_sub_value
    sub_value = self._sub_all_refs(sub_value, handler_method)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\intrinsics\actions.py", line 378, in _sub_all_refs
    return re.sub(
  File "re.py", line 210, in sub
TypeError: sequence item 1: expected str instance, int found

### Expected result:
sam validate --template buggy-template.yaml
2021-07-16 08:59:21 Loading policies from IAM...
2021-07-16 08:59:22 Finished loading policies from IAM.
C:\Projects\buggy-template.yaml is a valid SAM Template

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. If using SAM CLI, `sam --version`: 1.26.0
3. AWS region: us-east-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by moelasmar** [comment]
Please use quotes for the parameter default value to indicate that it is a string, as the Yaml Parser will understand this value as integer value.

**Comment by MarkLedermannTR** [comment]
That workaround does resolve the issue.

However, should the parameter type declaration override the Yaml type determination, as the parameter type is specified as String? Thanks

**Comment by moelasmar** [comment]
Thanks @MarkLedermannTR for your question. currently we depend on YAML specs to determine the values and types of the parameters values, and so if the parameter value is a string, so it is better to set the value between quotes.
