### ISSUE TITLE
sam deploy fails - InvalidBucketName

### ISSUE THREAD

**Issue by pfilaretov** [aws/serverless-application-model#2139]
### Description:
I'm trying to go through [SAM Hello World Tutorial](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html). I'm doing basic things described, i.e.

```
sam init
cd sam-app
sam build
sam deploy --guided
```

However, deploy fails with the following error:

```
Error: Failed to create managed resources: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once
```

If I go to AWS CloudFormation Console, I can see the stack status is `ROLLBACK_COMPLETE`, and there is a `CREATE_FAILED` event for `SamCliSourceBucketBucketPolicy`, the reason is `The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName`

I haven't specified the bucket name explicitly, so not sure why SAM cannot create it with the valid name. 

### Steps to reproduce:
Run the following commands:
```
sam init
cd sam-app
sam build
sam deploy --guided
```

### Observed result:
`sam deploy` fails with error. Here is the full output of commands above with `--debug` flag specified:

```
C:\IdeaProjects>sam init --debug
2021-09-07 17:53:47,008 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-09-07 17:53:47,009 | Using config file: samconfig.toml, config environment: default
2021-09-07 17:53:47,009 | Expand command line arguments to:
2021-09-07 17:53:47,009 | --package_type=Zip --output_dir=.
Which template source would you like to use?
        1 - AWS Quick Start Templates
        2 - Custom Template Location
Choice: 1
What package type would you like to use?
        1 - Zip (artifact is a zip uploaded to S3)
        2 - Image (artifact is an image uploaded to an ECR image repository)
Package type: 1

Which runtime would you like to use?
        1 - nodejs14.x
        2 - python3.9
        3 - ruby2.7
        4 - go1.x
        5 - java11
        6 - dotnetcore3.1
        7 - nodejs12.x
        8 - nodejs10.x
        9 - python3.8
        10 - python3.7
        11 - python3.6
        12 - python2.7
        13 - ruby2.5
        14 - java8.al2
        15 - java8
        16 - dotnetcore2.1
Runtime: 5

Which dependency manager would you like to use?
        1 - maven
        2 - gradle
Dependency manager: 1

Project name [sam-app]:
2021-09-07 17:54:10,972 |
Cloning from https://github.com/aws/aws-sam-cli-app-templates
2021-09-07 17:54:28,066 | Removing old repo at C:\Users\<user>\AppData\Roaming\AWS SAM\aws-sam-cli-app-templates
2021-09-07 17:54:28,790 | Copying from C:\Users\<user>\AppData\Local\Temp\tmpstigoflb\aws-sam-cli-app-templates to C:\Users\<user>\AppData\Roaming\AWS SAM\aws-sam-cli-app-templates

AWS quick start application templates:
        1 - Hello World Example: Maven
        2 - EventBridge Hello World: Maven
        3 - EventBridge App from scratch (100+ Event Schemas): Maven
        4 - Step Functions Sample App (Stock Trader): Maven
Template selection: 1

    -----------------------
    Generating application:
    -----------------------
    Name: sam-app
    Runtime: java11
    Dependency Manager: maven
    Application Template: hello-world
    Output Directory: .

    Next steps can be found in the README file at ./sam-app/README.md

2021-09-07 17:54:47,009 | Parameters dict created with input given
2021-09-07 17:54:47,014 | {'template': 'C:\\Users\\<user>\\AppData\\Roaming\\AWS SAM\\aws-sam-cli-app-templates\\java11/cookiecutter-aws-sam-hello-java-maven', 'output_dir': '.', 'no_input': True, 'extra_context': {'project_name': 'sam-app', 'runtime': 'java11'}}
2021-09-07 17:54:47,015 | Baking a new template with cookiecutter with all parameters
2021-09-07 17:54:49,383 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '...', 'installationId': '...', 'sessionId': '...', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.30.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam init', 'duration': 62374, 'exitReason': 'success', 'exitCode': 0}}]}
2021-09-07 17:54:50,258 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)


C:\IdeaProjects>cd sam-app


C:\IdeaProjects\sam-app>sam build --debug
2021-09-07 17:55:30,930 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-09-07 17:55:30,931 | Using config file: samconfig.toml, config environment: default
2021-09-07 17:55:30,931 | Expand command line arguments to:
2021-09-07 17:55:30,932 | --template_file=C:\IdeaProjects\sam-app\template.yaml --build_dir=.aws-sam\build --cache_dir=.aws-sam\cache
2021-09-07 17:55:31,150 | 'build' command is called
2021-09-07 17:55:31,168 | No Parameters detected in the template
2021-09-07 17:55:31,196 | 2 stacks found in the template
2021-09-07 17:55:31,197 | No Parameters detected in the template
2021-09-07 17:55:31,216 | 2 resources found in the stack
2021-09-07 17:55:31,216 | No Parameters detected in the template
2021-09-07 17:55:31,234 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2021-09-07 17:55:31,235 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to C:\IdeaProjects\sam-app\template.yaml
2021-09-07 17:55:31,235 | No Parameters detected in the template
2021-09-07 17:55:31,263 | Instantiating build definitions
2021-09-07 17:55:31,263 | No previous build graph found, generating new one
2021-09-07 17:55:31,264 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(java11, C:\IdeaProjects\sam-app\HelloWorldFunction, Zip, , <ID>, {}, {}, []), Function: Function(name='HelloWorldFunction', functionname='HelloWorldFunction', runtime='java11', memory=512, timeout=20, handler='helloworld.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='C:\\IdeaProjects\\sam-app\\HelloWorldFunction', environment={'Variables': {'PARAM1': 'VALUE'}}, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api', 'Properties': {'Path': '/hello', 'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None, inlinecode=None, codesign_config_arn=None, stack_path=''))
2021-09-07 17:55:31,266 | Building codeuri: C:\IdeaProjects\sam-app\HelloWorldFunction runtime: java11 metadata: {} functions: ['HelloWorldFunction']
2021-09-07 17:55:31,270 | Building to following folder C:\IdeaProjects\sam-app\.aws-sam\build\HelloWorldFunction
2021-09-07 17:55:31,271 | Looking for a supported build workflow in following directories: ['C:\\IdeaProjects\\sam-app\\HelloWorldFunction', 'C:\\IdeaProjects\\sam-app']
2021-09-07 17:55:31,273 | Loading workflow module 'aws_lambda_builders.workflows'
2021-09-07 17:55:31,288 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-09-07 17:55:31,295 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2021-09-07 17:55:31,302 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2021-09-07 17:55:31,309 | Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
2021-09-07 17:55:31,316 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2021-09-07 17:55:31,325 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2021-09-07 17:55:31,334 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2021-09-07 17:55:31,342 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2021-09-07 17:55:31,350 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2021-09-07 17:55:31,350 | Found workflow 'JavaMavenWorkflow' to support capabilities 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2021-09-07 17:55:31,691 | Running workflow 'JavaMavenWorkflow'
2021-09-07 17:55:31,691 | Running JavaMavenWorkflow:CopySource
2021-09-07 17:55:31,703 | JavaMavenWorkflow:CopySource succeeded
2021-09-07 17:55:31,703 | Running JavaMavenWorkflow:MavenBuild
2021-09-07 17:55:37,069 | Maven logs: [INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< helloworld:HelloWorld >------------------------
[INFO] Building A sample Hello World created for SAM CLI. 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ HelloWorld ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ HelloWorld ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ HelloWorld ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ HelloWorld ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ HelloWorld ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ HelloWorld ---
[INFO] Surefire report directory: C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running helloworld.AppTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.164 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ HelloWorld ---
[INFO] Building jar: C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\target\HelloWorld-1.0.jar
[INFO]
[INFO] --- maven-shade-plugin:3.2.4:shade (default) @ HelloWorld ---
[INFO] Including com.amazonaws:aws-lambda-java-core:jar:1.2.1 in the shaded jar.
[INFO] Including com.amazonaws:aws-lambda-java-events:jar:3.6.0 in the shaded jar.
[INFO] Including joda-time:joda-time:jar:2.6 in the shaded jar.
[WARNING] HelloWorld-1.0.jar, aws-lambda-java-core-1.2.1.jar, aws-lambda-java-events-3.6.0.jar, joda-time-2.6.jar define 1 overlapping resource:
[WARNING]   - META-INF/MANIFEST.MF
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\target\HelloWorld-1.0.jar with C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\target\HelloWorld-1.0-shaded.jar
[INFO] Dependency-reduced POM written at: C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\dependency-reduced-pom.xml
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ HelloWorld ---
[INFO] Installing C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\target\HelloWorld-1.0.jar to C:\Users\<user>\.m2\repository\helloworld\HelloWorld\1.0\HelloWorld-1.0.jar
[INFO] Installing C:\Users\<user>\AppData\Local\Temp\tmpvdlsemeo\dependency-reduced-pom.xml to C:\Users\<user>\.m2\repository\helloworld\HelloWorld\1.0\HelloWorld-1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.141 s
[INFO] Finished at: 2021-09-07T17:55:36+03:00
[INFO] ------------------------------------------------------------------------
2021-09-07 17:55:37,070 | JavaMavenWorkflow:MavenBuild succeeded
2021-09-07 17:55:37,075 | Running JavaMavenWorkflow:MavenCopyDependency
2021-09-07 17:55:39,671 | JavaMavenWorkflow:MavenCopyDependency succeeded
2021-09-07 17:55:39,671 | Running JavaMavenWorkflow:MavenCopyArtifacts
2021-09-07 17:55:39,688 | JavaMavenWorkflow:MavenCopyArtifacts succeeded

Build Succeeded

Built Artifacts  : .aws-sam\build
Built Template   : .aws-sam\build\template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided

2021-09-07 17:55:39,705 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '...', 'installationId': '...', 'sessionId': '...', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.30.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 8773, 'exitReason': 'success', 'exitCode': 0}}]}
2021-09-07 17:55:40,485 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)


C:\IdeaProjects\sam-app>sam deploy --guided --debug
2021-09-07 17:56:43,809 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-09-07 17:56:43,810 | Using config file: samconfig.toml, config environment: default
2021-09-07 17:56:43,811 | Expand command line arguments to:
2021-09-07 17:56:43,816 | --guided --template_file=C:\IdeaProjects\sam-app\.aws-sam\build\template.yaml --stack_name=sam-app --fail_on_empty_changeset

Configuring SAM deploy
======================

        Looking for config file [samconfig.toml] :  Not found

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [sam-app]:
        AWS Region [us-east-1]:
2021-09-07 17:56:47,802 | No Parameters detected in the template
2021-09-07 17:56:47,830 | 2 stacks found in the template
        #Shows you resources changes to be deployed and require a 'Y' to initiate deploy
        Confirm changes before deploy [y/N]: y
        #SAM needs permission to be able to create roles to connect to the resources in your template
        Allow SAM CLI IAM role creation [Y/n]: y
2021-09-07 17:56:53,474 | No Parameters detected in the template
2021-09-07 17:56:53,507 | 2 resources found in the stack
2021-09-07 17:56:53,507 | No Parameters detected in the template
2021-09-07 17:56:53,527 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2021-09-07 17:56:53,527 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to C:\IdeaProjects\sam-app\.aws-sam\build\template.yaml
2021-09-07 17:56:53,528 | No Parameters detected in the template
2021-09-07 17:56:53,548 | Detected Inline Swagger definition
2021-09-07 17:56:53,549 | Auth checks done on swagger are not exhaustive!
        HelloWorldFunction may not have authorization defined, Is this okay? [y/N]: y
2021-09-07 17:56:56,003 | No Parameters detected in the template
2021-09-07 17:56:56,036 | 2 resources found in the stack
2021-09-07 17:56:56,036 | No Parameters detected in the template
2021-09-07 17:56:56,062 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2021-09-07 17:56:56,062 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to C:\IdeaProjects\sam-app\.aws-sam\build\template.yaml
2021-09-07 17:56:56,062 | No function or layer definition found with code sign config, skipping
        Save arguments to configuration file [Y/n]: y
        SAM configuration file [samconfig.toml]:
        SAM configuration environment [default]:

        Looking for resources needed for deployment:
2021-09-07 17:57:01,252 | Managed S3 stack [aws-sam-cli-managed-default] not found. Creating a new one.
        Creating the required resources...
2021-09-07 17:57:34,918 | Failed to create managed resources
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\managed_cloudformation_stack.py", line 107, in _create_or_get_stack
    stack = _create_stack(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\managed_cloudformation_stack.py", line 180, in _create_stack
    stack_waiter.wait(StackName=stack_id, WaiterConfig={"Delay": 15, "MaxAttempts": 60})
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\waiter.py", line 350, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once
2021-09-07 17:57:34,926 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '...', 'installationId': '...', 'sessionId': '...', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.30.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam deploy', 'duration': 51114, 'exitReason': 'ManagedStackError', 'exitCode': 1}}]}
2021-09-07 17:57:35,764 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create managed resources: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once
```

### Expected result:
Tutorial app is deployed successfully.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. If using SAM CLI, `sam --version`:
```
> sam --version
SAM CLI, version 1.30.0
```
3. AWS region: `us-east-1`

**Comment by sriram-mv** [comment]
@pfilaretov Is this related to https://github.com/aws/aws-sam-cli/issues/3243 or are you seeing a completely different issue?

What does the `aws-sam-cli-managed-default` stack events say?  do they say "The specified bucket is not valid."

**Comment by pfilaretov** [comment]
@sriram-mv , thank you, this is exactly the same issue.
The failed event is `The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName`
