### ISSUE TITLE
Spring functional beans not accessible through request headers

### ISSUE THREAD

**Issue by Conrad-Fat-Potato-UK** [aws/serverless-application-model#2267]
### Description:

I can deploy my JAR file to Lambda manually and my tests are successful. However, when using SAM it fails. This includes doing so with `sam local invoke`, `sam deploy`, as well as `sam local start-api`. 

The problem is down to the required header "spring.cloud.function.definition", which I am unable to attach when using SAM. 

### Steps to reproduce:

**POM**
```
<properties>
  <java.version>11</java.version>
  <maven.compiler.target>11</maven.compiler.target>
  <spring-cloud-function.version>3.1.5</spring-cloud-function.version>
  <wrapper.version>1.0.27.RELEASE</wrapper.version>
</properties>
<dependencies>
  <dependency>
	  <groupId>org.springframework.boot</groupId>
	  <artifactId>spring-boot-starter-web</artifactId>
  </dependency>
  <dependency>
	  <groupId>org.springframework.cloud</groupId>
	  <artifactId>spring-cloud-function-web</artifactId>
  </dependency>
  <dependency>
	  <groupId>org.springframework.cloud</groupId>
	  <artifactId>spring-cloud-function-adapter-aws</artifactId>
	  <version>3.1.5</version>
  </dependency>
  <dependency>
	  <groupId>org.projectlombok</groupId>
	  <artifactId>lombok</artifactId>
	  <version>1.18.20</version>
  </dependency>
  <dependency>
	  <groupId>org.springframework.boot</groupId>
	  <artifactId>spring-boot-starter-test</artifactId>
	  <scope>test</scope>
  </dependency>
</dependencies>

<dependencyManagement>
  <dependencies>
	  <dependency>
		  <groupId>org.springframework.cloud</groupId>
		  <artifactId>spring-cloud-function-dependencies</artifactId>
		  <version>${spring-cloud-function.version}</version>
		  <type>pom</type>
		  <scope>import</scope>
	  </dependency>
  </dependencies>
</dependencyManagement>

<build>
<plugins>
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-deploy-plugin</artifactId>
		<configuration>
			<skip>true</skip>
		</configuration>
	</plugin>
	<plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot.experimental</groupId>
				<artifactId>spring-boot-thin-layout</artifactId>
				<version>${wrapper.version}</version>
			</dependency>
		</dependencies>
	</plugin>
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-shade-plugin</artifactId>
		<version>3.2.4</version>
		<configuration>
			<createDependencyReducedPom>false</createDependencyReducedPom>
			<shadedArtifactAttached>true</shadedArtifactAttached>
			<shadedClassifierName>aws</shadedClassifierName>
		</configuration>
	</plugin>
</plugins>
</build>

<repositories>
<repository>
	<id>spring-milestones</id>
	<name>Spring Milestones</name>
	<url>https://repo.spring.io/milestone</url>
	<snapshots>
		<enabled>false</enabled>
	</snapshots>
</repository>
</repositories>
```

**Main Java Class**
```import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.List;
import java.util.function.Function;
import java.util.function.Supplier;


@SpringBootApplication
public class SpringvApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringvApplication.class, args);
	}

	@Bean
	public Function<String, String> hiBean() {
		return value -> {
			return "Bean says hi :)";
		};
	}
}
```

**template.yaml**
```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Repeatable lambda deployment demo

Globals:
  Function:
    Timeout: 15

Resources:
  SAMbda: 
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SAMbda 
      CodeUri:
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:

        GetHi:
          Type: Api
          Properties:
            Path: /hiBean # URL Path here
            Method: get
```

### Observed result:
```  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.1)

2021-12-16 16:39:14.030  INFO 16 --- [           main] o.s.c.f.a.aws.CustomRuntimeInitializer   : AWS Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
2021-12-16 16:39:14.082  INFO 16 --- [           main] lambdainternal.AWSLambda                 : Starting AWSLambda using Java 11.0.12 on 223c2d245a92 with PID 16 (/var/runtime/lib/aws-lambda-java-runtime-0.2.0.jar started by root in /var/task)
2021-12-16 16:39:14.084  INFO 16 --- [           main] lambdainternal.AWSLambda                 : No active profile set, falling back to default profiles: default
2021-12-16 16:39:16.881  INFO 16 --- [           main] lambdainternal.AWSLambda                 : Started AWSLambda in 5.453 seconds (JVM running for 7.351)
2021-12-16 16:39:16.888  INFO 16 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Locating function: 'null'
2021-12-16 16:39:16.892  INFO 16 --- [           main] c.f.c.c.BeanFactoryAwareFunctionRegistry : Can't determine default function definition. Please use 'spring.cloud.function.definition' property to explicitly define it.
2021-12-16 16:39:16.892  INFO 16 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Will default to RoutingFunction, since it is the only function available in FunctionCatalog.Expecting 'spring.cloud.function.definition' or 'spring.cloud.function.routing-expression' as Message headers. If invocation is over API Gateway, Message headers can be provided as HTTP headers.
2021-12-16 16:39:16.932  INFO 16 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Located function: 'functionRouter'
2021-12-16 16:39:16.949  INFO 16 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Received: {
  "httpMethod": "GET",
  "path": "/hiBean",
  "headers": {
    "spring.cloud.function.definition": "hiBean"
  }
}
2021-12-16 16:39:16.972  INFO 16 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming JSON Event: {
  "httpMethod": "GET",
  "path": "/hiBean",
  "headers": {
    "spring.cloud.function.definition": "hiBean"
  }
}
2021-12-16 16:39:17.127  INFO 16 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming MAP: {httpMethod=GET, path=/hiBean, headers={spring.cloud.function.definition=hiBean}}
2021-12-16 16:39:17.127  INFO 16 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming request is API Gateway
2021-12-16 16:39:17.139  INFO 16 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Body is [B@66908383
2021-12-16 16:39:17.151  INFO 16 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming request headers: {id=1c9591c7-a690-a5d8-88dd-d16931f07888, timestamp=1639672756966}
Failed to lookup function to route based on the value of 'spring.cloud.function.definition' property 'null': java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: Failed to lookup function to route based on the value of 'spring.cloud.function.definition' property 'null'
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.springframework.cloud.function.context.config.RoutingFunction.functionFromDefinition(RoutingFunction.java:187)
	at org.springframework.cloud.function.context.config.RoutingFunction.route(RoutingFunction.java:111)
	at org.springframework.cloud.function.context.config.RoutingFunction.apply(RoutingFunction.java:84)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:672)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:524)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.handleRequest(FunctionInvoker.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

END RequestId: 9a880793-98ac-4dc6-aca2-4150b913e64d
REPORT RequestId: 9a880793-98ac-4dc6-aca2-4150b913e64d	Init Duration: 0.64 ms	Duration: 7812.93 ms	Billed Duration: 7813 ms	Memory Size: 512 MB	Max Memory Used: 512 MB	
{"errorMessage":"Failed to lookup function to route based on the value of 'spring.cloud.function.definition' property 'null'","errorType":"java.lang.IllegalArgumentException","stackTrace":["org.springframework.util.Assert.notNull(Assert.java:201)","org.springframework.cloud.function.context.config.RoutingFunction.functionFromDefinition(RoutingFunction.java:187)","org.springframework.cloud.function.context.config.RoutingFunction.route(RoutingFunction.java:111)","org.springframework.cloud.function.context.config.RoutingFunction.apply(RoutingFunction.java:84)","org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:672)","org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:524)","org.springframework.cloud.function.adapter.aws.FunctionInvoker.handleRequest(FunctionInvoker.java:85)","java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)","java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)","java.base/java.lang.reflect.Method.invoke(Unknown Source)"]}2021-12-16 16:39:17,511 | Cleaning all decompressed code dirs
2021-12-16 16:39:17,512 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '9ed97be6-e1ea-4e88-8df3-cd6bc55c477b', 'installationId': '1a786c9d-cb49-4a4f-960f-5b103b3f6020', 'sessionId': '194e9840-31c9-451c-a1e3-1e311554e886', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.12', 'samcliVersion': '1.36.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 8502, 'exitReason': 'success', 'exitCode': 0}}]}
2021-12-16 16:39:18,091 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2021-12-16 16:39:18,091 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-12-16 16:39:18,091 | Sending Telemetry: {'metrics': [{'runtimeMetric': {'requestId': 'c0828887-6889-4bce-a532-51ce6c779752', 'installationId': '1a786c9d-cb49-4a4f-960f-5b103b3f6020', 'sessionId': '194e9840-31c9-451c-a1e3-1e311554e886', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.12', 'samcliVersion': '1.36.0', 'runtimes': ['java11']}}]}
2021-12-16 16:39:18,665 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

### Expected result:
Output of "Bean says hi :)"

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS
2. If using SAM CLI, `sam --version`: 1.36.0
3. AWS region: eu-west-2

**Comment by awood45** [comment]
I'm slightly confused, due to not having a background with Spring - where is the header attached in normal running. Do we expect it to be present in the request via API Gateway? Is it "injected" by something but not part of the request?

**Comment by mndeveci** [comment]
When you start your function, spring prints out couple of messages (before the Spring banner) and they are all related to searching for main class of the Spring Boot application. In order to fix this issue, main class information should be passed to lambda environment. You can do this by adding a new environment variable to function. I couldn't get this work by placing the class in the root folder, so you need to move your class into a package (here I set it to `com.mnd`) as well.

Here is the updated resource section in `template.yaml` file.

```
Resources:
  SAMbda: 
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SAMbda 
      CodeUri: spring_test
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment:
        Variables:
          MAIN_CLASS: "com.mnd.SpringvApplication"
      Events:
        GetHi:
          Type: Api
          Properties:
            Path: /hiBean # URL Path here
            Method: get
```

After updating this, I was able to run the function with `sam local invoke` and `sam local start-api`.

#### `sam local invoke`
```
Invoking org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest (java11)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-java11:rapid-1.36.0-x86_64.

Mounting aws-sam/build/SAMbda as /var/task:ro,delegated inside runtime container
21:44:58.180 [main] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Main class: class com.mnd.SpringvApplication
21:44:58.187 [main] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Main class: class com.mnd.SpringvApplication

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.5)

2021-12-20 21:44:59.905  INFO 14 --- [           main] o.s.c.f.a.aws.CustomRuntimeInitializer   : AWS Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
2021-12-20 21:44:59.949  INFO 14 --- [           main] lambdainternal.AWSLambda                 : Starting AWSLambda using Java 11.0.12 on 0225c6a704b0 with PID 14 (/var/runtime/lib/aws-lambda-java-runtime-0.2.0.jar started by root in /var/task)
2021-12-20 21:44:59.951  INFO 14 --- [           main] lambdainternal.AWSLambda                 : No active profile set, falling back to default profiles: default
2021-12-20 21:45:01.589  INFO 14 --- [           main] lambdainternal.AWSLambda                 : Started AWSLambda in 3.077 seconds (JVM running for 3.971)
2021-12-20 21:45:01.593  INFO 14 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Locating function: 'null'
2021-12-20 21:45:01.610  INFO 14 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Located function: 'hiBean'
2021-12-20 21:45:01.617  INFO 14 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Received: {}
2021-12-20 21:45:01.627  INFO 14 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming JSON Event: {}
2021-12-20 21:45:01.709  INFO 14 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming MAP: {}
2021-12-20 21:45:01.714  INFO 14 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming request headers: {id=b623da38-ab89-aa3e-1b40-f7feb87fdcc7, timestamp=1640036701624}
END RequestId: 8612dd50-9209-4397-a7bd-ace7ef52c2f0
REPORT RequestId: 8612dd50-9209-4397-a7bd-ace7ef52c2f0  Init Duration: 0.16 ms  Duration: 4121.18 ms    Billed Duration: 4122 ms        Memory Size: 512 MBMax Memory Used: 512 MB
"Bean says hi :)"%   
```


#### `sam local start-api`
```
Mounting SAMbda at http://127.0.0.1:3000/hiBean [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2021-12-20 13:46:31  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
Invoking org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest (java11)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-java11:rapid-1.36.0-x86_64.

Mounting .aws-sam/build/SAMbda as /var/task:ro,delegated inside runtime container
START RequestId: 4d576854-902a-4560-81e8-0e6c873599b5 Version: $LATEST
21:46:46.585 [main] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Main class: class com.mnd.SpringvApplication
21:46:46.592 [main] INFO org.springframework.cloud.function.utils.FunctionClassUtils - Main class: class com.mnd.SpringvApplication

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.5)

2021-12-20 21:46:48.495  INFO 15 --- [           main] o.s.c.f.a.aws.CustomRuntimeInitializer   : AWS Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
2021-12-20 21:46:48.527  INFO 15 --- [           main] lambdainternal.AWSLambda                 : Starting AWSLambda using Java 11.0.12 on 8991fc467e36 with PID 15 (/var/runtime/lib/aws-lambda-java-runtime-0.2.0.jar started by root in /var/task)
2021-12-20 21:46:48.528  INFO 15 --- [           main] lambdainternal.AWSLambda                 : No active profile set, falling back to default profiles: default
2021-12-20 21:46:50.880  INFO 15 --- [           main] lambdainternal.AWSLambda                 : Started AWSLambda in 3.946 seconds (JVM running for 4.939)
2021-12-20 21:46:50.883  INFO 15 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Locating function: 'null'
2021-12-20 21:46:50.904  INFO 15 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Located function: 'hiBean'
2021-12-20 21:46:50.911  INFO 15 --- [           main] o.s.c.f.adapter.aws.FunctionInvoker      : Received: {"body": null, "headers": {"Accept": "*/*", "Host": "localhost:3000", "User-Agent": "curl/7.64.1", "X-Forwarded-Port": "3000", "X-Forwarded-Proto": "http"}, "httpMethod": "GET", "isBase64Encoded": false, "multiValueHeaders": {"Accept": ["*/*"], "Host": ["localhost:3000"], "User-Agent": ["curl/7.64.1"], "X-Forwarded-Port": ["3000"], "X-Forwarded-Proto": ["http"]}, "multiValueQueryStringParameters": null, "path": "/hiBean", "pathParameters": null, "queryStringParameters": null, "requestContext": {"accountId": "123456789012", "apiId": "1234567890", "domainName": "localhost:3000", "extendedRequestId": null, "httpMethod": "GET", "identity": {"accountId": null, "apiKey": null, "caller": null, "cognitoAuthenticationProvider": null, "cognitoAuthenticationType": null, "cognitoIdentityPoolId": null, "sourceIp": "127.0.0.1", "user": null, "userAgent": "Custom User Agent String", "userArn": null}, "path": "/hiBean", "protocol": "HTTP/1.1", "requestId": "f9e4fdf2-a74e-4115-a8a7-c2bce336a74d", "requestTime": "20/Dec/2021:21:46:31 +0000", "requestTimeEpoch": 1640036791, "resourceId": "123456", "resourcePath": "/hiBean", "stage": "Prod"}, "resource": "/hiBean", "stageVariables": null, "version": "1.0"}
2021-12-20 21:46:50.925  INFO 15 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming JSON Event: {"body": null, "headers": {"Accept": "*/*", "Host": "localhost:3000", "User-Agent": "curl/7.64.1", "X-Forwarded-Port": "3000", "X-Forwarded-Proto": "http"}, "httpMethod": "GET", "isBase64Encoded": false, "multiValueHeaders": {"Accept": ["*/*"], "Host": ["localhost:3000"], "User-Agent": ["curl/7.64.1"], "X-Forwarded-Port": ["3000"], "X-Forwarded-Proto": ["http"]}, "multiValueQueryStringParameters": null, "path": "/hiBean", "pathParameters": null, "queryStringParameters": null, "requestContext": {"accountId": "123456789012", "apiId": "1234567890", "domainName": "localhost:3000", "extendedRequestId": null, "httpMethod": "GET", "identity": {"accountId": null, "apiKey": null, "caller": null, "cognitoAuthenticationProvider": null, "cognitoAuthenticationType": null, "cognitoIdentityPoolId": null, "sourceIp": "127.0.0.1", "user": null, "userAgent": "Custom User Agent String", "userArn": null}, "path": "/hiBean", "protocol": "HTTP/1.1", "requestId": "f9e4fdf2-a74e-4115-a8a7-c2bce336a74d", "requestTime": "20/Dec/2021:21:46:31 +0000", "requestTimeEpoch": 1640036791, "resourceId": "123456", "resourcePath": "/hiBean", "stage": "Prod"}, "resource": "/hiBean", "stageVariables": null, "version": "1.0"}
2021-12-20 21:46:51.012  INFO 15 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming MAP: {body=null, headers={Accept=*/*, Host=localhost:3000, User-Agent=curl/7.64.1, X-Forwarded-Port=3000, X-Forwarded-Proto=http}, httpMethod=GET, isBase64Encoded=false, multiValueHeaders={Accept=[*/*], Host=[localhost:3000], User-Agent=[curl/7.64.1], X-Forwarded-Port=[3000], X-Forwarded-Proto=[http]}, multiValueQueryStringParameters=null, path=/hiBean, pathParameters=null, queryStringParameters=null, requestContext={accountId=123456789012, apiId=1234567890, domainName=localhost:3000, extendedRequestId=null, httpMethod=GET, identity={accountId=null, apiKey=null, caller=null, cognitoAuthenticationProvider=null, cognitoAuthenticationType=null, cognitoIdentityPoolId=null, sourceIp=127.0.0.1, user=null, userAgent=Custom User Agent String, userArn=null}, path=/hiBean, protocol=HTTP/1.1, requestId=f9e4fdf2-a74e-4115-a8a7-c2bce336a74d, requestTime=20/Dec/2021:21:46:31 +0000, requestTimeEpoch=1640036791, resourceId=123456, resourcePath=/hiBean, stage=Prod}, resource=/hiBean, stageVariables=null, version=1.0}
2021-12-20 21:46:51.012  INFO 15 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming request is API Gateway
2021-12-20 21:46:51.017  INFO 15 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Body is [B@73eb8672
2021-12-20 21:46:51.023  INFO 15 --- [           main] o.s.c.f.adapter.aws.AWSLambdaUtils       : Incoming request headers: {id=489dd8ff-e8c1-6048-cbb1-fccc6ca9ef1b, timestamp=1640036810921}
END RequestId: 4d576854-902a-4560-81e8-0e6c873599b5
REPORT RequestId: 4d576854-902a-4560-81e8-0e6c873599b5  Init Duration: 0.38 ms  Duration: 5163.18 ms    Billed Duration: 5164 ms        Memory Size: 512 MBMax Memory Used: 512 MB
No Content-Type given. Defaulting to 'application/json'.
2021-12-20 13:46:51 127.0.0.1 - - [20/Dec/2021 13:46:51] "GET /hiBean HTTP/1.1" 200 -
```

With `sam local start-api`, you can invoke function by running `curl localhost:3000/hiBean`


Please let us know if you have further questions.

**Comment by vitalychernov** [comment]
@mndeveci @mndeveci I'm having the same issue, and I'm trying to reproduce the code, but I'm getting the following error 

`Invoking org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest (java11)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-java11:rapid-1.53.0-x86_64.

Mounting C:\Users\dpvitaly\projects\untitled\HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: 3070841f-6b6a-4440-843d-a077f0c8f0c5 Version: $LATEST
Class not found: org.springframework.cloud.function.adapter.aws.FunctionInvoker: java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: org.springframework.cloud.function.adapter.aws.FunctionInvoker. Current classpath: file:/var/task/

END RequestId: 3070841f-6b6a-4440-843d-a077f0c8f0c5
REPORT RequestId: 3070841f-6b6a-4440-843d-a077f0c8f0c5  Init Duration: 0.11 ms  Duration: 151.86 ms     Billed Duration: 152 ms Memory Size: 512 MB     Max Memory Used: 512 MB
{"errorMessage":"Class not found: org.springframework.cloud.function.adapter.aws.FunctionInvoker","errorType":"java.lang.ClassNotFoundException"}
`

**Comment by vitalychernov** [comment]
@mndeveci @mildaniel I'm trying to reproduce the code, as I have similar issue and I'm getting the error message

**sam local invoke**
> Invoking org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest (java11)
> Skip pulling image and use local one: public.ecr.aws/sam/emulation-java11:rapid-1.53.0-x86_64.
> 
> Mounting C:\Users\dpvitaly\projects\demo2 as /var/task:ro,delegated inside runtime container
> START RequestId: 4ad80092-d88c-45e8-8983-d67888f8aab9 Version: $LATEST
> Class not found: org.springframework.cloud.function.adapter.aws.FunctionInvoker: java.lang.ClassNotFoundException
> java.lang.ClassNotFoundException: org.springframework.cloud.function.adapter.aws.FunctionInvoker. Current classpath: file:/var/task/
> 
> END RequestId: 4ad80092-d88c-45e8-8983-d67888f8aab9
> REPORT RequestId: 4ad80092-d88c-45e8-8983-d67888f8aab9  Init Duration: 0.09 ms  Duration: 151.02 ms     Billed Duration: 152 ms Memory Size: 512 MB     Max Memory Used: 512 MB
> {"errorMessage":"Class not found: org.springframework.cloud.function.adapter.aws.FunctionInvoker","errorType":"java.lang.ClassNotFoundException"}

Do you have simple "Bean says hi :)" repo, that I can take a look and see what's the problem
