### ISSUE TITLE
No module named 'samtranslator.utils.py27hash_fix'

### ISSUE THREAD

**Issue by underdog681** [aws/serverless-application-model#2381]
### Description:
After installing sam cli via brew I get the following error when running 'sam --version'
I am using these instructions https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 5, in <module>
    from samcli.cli.main import cli
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 11, in <module>
    from samcli.lib.telemetry.metric import send_installed_metric, emit_all_metrics
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 20, in <module>
    from samcli.commands._utils.experimental import get_all_experimental_statues
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/_utils/experimental.py", line 14, in <module>
    from samcli.commands._utils.options import parameterized_option
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/_utils/options.py", line 13, in <module>
    from samcli.commands._utils.template import get_template_data, TemplateNotFoundException
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/_utils/template.py", line 15, in <module>
    from samcli.yamlhelper import yaml_parse, yaml_dump
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/yamlhelper.py", line 24, in <module>
    from samtranslator.utils.py27hash_fix import Py27Dict, Py27UniStr
ModuleNotFoundError: No module named 'samtranslator.utils.py27hash_fix'

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Monterey v 12.3
2. If using SAM CLI, `sam --version`: Not available 
3. AWS region: us-west-2

`Add --debug flag to any SAM CLI commands you are running`

**Comment by moelasmar** [comment]
Thanks @underdog681 for raising this issue. This issue is related to SAM CLI repository, I will move it.
