### ISSUE TITLE
AutoPublishAlias + VersionDescription: fails to modify existing version instead of creating new version (or skipping update)

### ISSUE THREAD

**Issue by mariaines** [aws/serverless-application-model#2786]
### Description:
We have a deployment pipeline that deploys a backend SAM stack first, then a separate frontend stack. Occasionally we have changes that only touch the frontend stack - when that happens, the backend stack gets deployed with a new parameter (`Revision`) but no other changes. This `Revision` param is set as `VersionDescription` for various Lambdas with AutoPublishAlias.

What we are seeing is that frontend-only changes are failing upon deploying the backend stack, with "Internal Failure" on FunctionVersion updates. My understanding is that "Internal Failure" means Lambda is rejecting the update since nothing has changed. But I don't understand why SAM is attempting to deploy a new version at all? Is it because of the changing `VersionDescription`? If so, do you have a recommendation for a workaround for this sort of scenario?

Also, I noticed that on deploying these changes, SAM is attempting to _modify_ an existing FunctionVersion. Shouldn't it be either 1) creating a new version or 2) skipping the update completely? I thought a FunctionVersion is essentially immutable?

### Steps to reproduce:
I created a demo repo here: https://github.com/mariaines/sam-autopublishalias-failure
```sh
git checkout v1
sam build -u
sam deploy   # should succeed
git checkout v2
sam build -u
sam deploy   # fails with "Internal Failure" attempting to update a FunctionVersion
```

### Observed result:
SAM stack fails to deploy with "Internal Failure" due to attempting to modify an existing FunctionVersion with no changes.
```sh
$ sam deploy --debug --guided
2021-09-20 12:34:29,153 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-09-20 12:34:29,153 | Using config file: samconfig.toml, config environment: default
2021-09-20 12:34:29,154 | Expand command line arguments to:
2021-09-20 12:34:29,154 | --guided --template_file=/Users/mariaines/depot/sam-autopublishalias-failure/mariaines-test-sam/template.yaml --stack_name=mariaines-test-sam --s3_bucket=aws-sam-cli-managed-default-samclisourcebucket-1akqsmxlhmhg2 --s3_prefix=mariaines-test-sam --fail_on_empty_changeset --confirm_changeset --parameter_overrides={'Revision': '2'} --capabilities=['CAPABILITY_IAM']

Configuring SAM deploy
======================

	Looking for config file [samconfig.toml] :  Found
	Reading default arguments  :  Success

	Setting default arguments for 'sam deploy'
	=========================================
	Stack Name [mariaines-test-sam]:
	AWS Region [us-west-2]:
	Parameter Revision [2]:
2021-09-20 12:34:32,780 | Collected default values for parameters: {}
2021-09-20 12:34:32,810 | 2 stacks found in the template
	#Shows you resources changes to be deployed and require a 'Y' to initiate deploy
	Confirm changes before deploy [Y/n]: y
	#SAM needs permission to be able to create roles to connect to the resources in your template
	Allow SAM CLI IAM role creation [Y/n]: y
2021-09-20 12:34:35,360 | Collected default values for parameters: {}
2021-09-20 12:34:35,385 | 2 resources found in the stack
2021-09-20 12:34:35,386 | Collected default values for parameters: {}
2021-09-20 12:34:35,407 | Found Serverless function with name='HelloWorldFunction' and CodeUri='src/'
2021-09-20 12:34:35,408 | --base-dir is not presented, adjusting uri src/ relative to /Users/mariaines/depot/sam-autopublishalias-failure/mariaines-test-sam/template.yaml
2021-09-20 12:34:35,408 | Collected default values for parameters: {}
2021-09-20 12:34:35,429 | Detected Inline Swagger definition
2021-09-20 12:34:35,429 | Auth checks done on swagger are not exhaustive!
	HelloWorldFunction may not have authorization defined, Is this okay? [y/N]: y
2021-09-20 12:34:37,081 | Collected default values for parameters: {}
2021-09-20 12:34:37,107 | 2 resources found in the stack
2021-09-20 12:34:37,107 | Collected default values for parameters: {}
2021-09-20 12:34:37,131 | Found Serverless function with name='HelloWorldFunction' and CodeUri='src/'
2021-09-20 12:34:37,131 | --base-dir is not presented, adjusting uri src/ relative to /Users/mariaines/depot/sam-autopublishalias-failure/mariaines-test-sam/template.yaml
2021-09-20 12:34:37,131 | No function or layer definition found with code sign config, skipping
	Save arguments to configuration file [Y/n]: n

	Looking for resources needed for deployment: Found!

		Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-1akqsmxlhmhg2
		A different default S3 bucket can be set in samconfig.toml
2021-09-20 12:34:46,999 | File with same data is already exists at mariaines-test-sam/c6ce8fa8b5a97dd022ecd006536eb5a4. Skipping upload

	Deploying with following values
	===============================
	Stack name                   : mariaines-test-sam
	Region                       : us-west-2
	Confirm changeset            : True
	Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-1akqsmxlhmhg2
	Capabilities                 : ["CAPABILITY_IAM"]
	Parameter overrides          : {"Revision": "2"}
	Signing Profiles             : {}

Initiating deployment
=====================
2021-09-20 12:34:47,032 | Collected default values for parameters: {}
2021-09-20 12:34:47,056 | 2 stacks found in the template
2021-09-20 12:34:47,056 | Collected default values for parameters: {}
2021-09-20 12:34:47,076 | 2 resources found in the stack
2021-09-20 12:34:47,076 | Collected default values for parameters: {}
2021-09-20 12:34:47,639 | File with same data is already exists at mariaines-test-sam/afba18fb10d6f4ca990d5c818d75fdcc.template. Skipping upload

Waiting for changeset to be created..

CloudFormation stack changeset
-----------------------------------------------------------------------------------------------------
Operation                 LogicalResourceId         ResourceType              Replacement
-----------------------------------------------------------------------------------------------------
* Modify                  HelloWorldFunctionAlias   AWS::Lambda::Alias        False
                          live
* Modify                  HelloWorldFunctionVersi   AWS::Lambda::Version      False
                          on4b2f9c4e7c
-----------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-west-2:561883256160:changeSet/samcli-deploy1632166487/2a12bf83-db01-4a11-8aa0-6433afa80590


Previewing CloudFormation changeset before deployment
======================================================
Deploy this changeset? [y/N]: y

2021-09-20 12:35:29 - Waiting for stack create/update to complete

CloudFormation events from changeset
-----------------------------------------------------------------------------------------------------
ResourceStatus            ResourceType              LogicalResourceId         ResourceStatusReason
-----------------------------------------------------------------------------------------------------
UPDATE_FAILED             AWS::Lambda::Version      HelloWorldFunctionVersi   Internal Failure
                                                    on4b2f9c4e7c
UPDATE_IN_PROGRESS        AWS::Lambda::Version      HelloWorldFunctionVersi   -
                                                    on4b2f9c4e7c
UPDATE_ROLLBACK_IN_PROG   AWS::CloudFormation::St   mariaines-test-sam        The following
RESS                      ack                                                 resource(s) failed to
                                                                              update: [HelloWorldFunc
                                                                              tionVersion4b2f9c4e7c].
UPDATE_COMPLETE           AWS::Lambda::Version      HelloWorldFunctionVersi   -
                                                    on4b2f9c4e7c
UPDATE_ROLLBACK_COMPLET   AWS::CloudFormation::St   mariaines-test-sam        -
E_CLEANUP_IN_PROGRESS     ack
UPDATE_ROLLBACK_COMPLET   AWS::CloudFormation::St   mariaines-test-sam        -
E                         ack
-----------------------------------------------------------------------------------------------------
2021-09-20 12:35:48,143 | Execute changeset waiter exception
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/deploy/deployer.py", line 439, in wait_for_execute
    waiter.wait(StackName=stack_name, WaiterConfig=waiter_config)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/waiter.py", line 350, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter StackUpdateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "UPDATE_ROLLBACK_COMPLETE" at least once
2021-09-20 12:35:48,148 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'fbbe0f7f-f326-413a-a054-a08641386b0b', 'installationId': '42030402-1a1f-4d1b-866b-a80428759e30', 'sessionId': '8457faac-52bf-4217-b7dc-e829ae8e1ad2', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.10', 'samcliVersion': '1.24.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'us-west-2', 'commandName': 'sam deploy', 'duration': 78991, 'exitReason': 'DeployFailedError', 'exitCode': 1}}]}
2021-09-20 12:35:48,352 | Telemetry response: 200
Error: Failed to create/update the stack: mariaines-test-sam, Waiter StackUpdateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "UPDATE_ROLLBACK_COMPLETE" at least once
```

### Expected result:
SAM stack deploys successfully, skipping Version creation since there are no code changes.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Amazon Linux (aws/codebuild/standard:5.0)
2. `sam --version`: 1.31.0
3. AWS region: us-west-2

`Add --debug flag to command you are running`

**Comment by aaythapa** [comment]
If the issue is that changing the `VerisonDescription` won't deploy a new Lambda version thus causing deployment issues then that will be fixed with the new property introduced in this [PR](https://github.com/aws/serverless-application-model/pull/2838). Going to close this issue for now, please re-open if the issue persists.
